### ISSUE TITLE
Add deeper permission system

### ISSUE THREAD

**Issue by cmfcmf** [cmfcmf/MediaModule#10]
I need your help defining what the permission system should be able to deal with. 

#### What's currently implemented
You can set permissions based on group and object type using the PermissionsModule. For example:
- Give all guests display access to all the media files and collections but disallow downloading
- Allow all moderators to add / edit licenses but don't allow to add / edit watermarks

#### What's currently NOT implemented
You cannot set permissions per collection / medium. For example:
1. You cannot create private collections which only you yourself have access to.
2. You cannot restrict guests to see collection X while they are not allowed to see collection Y
3. You cannot password-protect collections and media
4. You cannot allow users to only upload to collection X
5. You cannot set a maximum file size for certain users / groups
6. You cannot set allowed file types by collection 
7. You cannot set a maximum size for all the uploaded media by a single user
8. You cannot restrict users to only use watermark / license X and not use watermark / license Y

#### What do we need?
- Do we need such a deep permission system based on *Media* or is based on *Collections* sufficient?
- What features do we actually need?

**Comment by Guite** [comment]
I think additional permission features should be based on collections. Doing it for single media items is probably going to waste too much performance.

**Comment by rallek** [comment]
In general I agree with Axel. 
In detail:
1. Private collections are not needed for me. If needed it can be managed via 2.
2. The module should manage the possibility to restrict a collection to be visible/ add possibilities for a dedicated group. And one generic permission to all collections without a specific permission.
3. not needed for me if 2. is implemented
4. can be managed with my proposal in 2.
5. Setting file size for all collections is needed. A setting of a maximum file size by collection is nice to have.
6. File types per collection should be managable. But not via permission, better via setting during creating a collection (for version 2)
7. is not needed but would be nice (version 2)
8. mmh, have no ideas about this

In total: number 2 is the most important permission for me but not limited to guests.

**Comment by cmfcmf** [comment]
One more question: If collection A has a subcollection B. If I now disallow access to collection A for a certain group, should that automatically disallow access to all child collections (i.e. B). It should, right?

**Comment by craigh** [comment]
tree structures are (IMO) inherently difficult to apply permissions to. Checking them also is hard because if you have extended families/trees, it becomes difficult to check all the levels involved.

**Comment by rallek** [comment]
But in general I would expact this behavior Christian is discribing.

**Comment by Guite** [comment]
Implementation should be possible using some kind of recursion: `$collection->isAllowed()` calls `isAllowed()` for all child collections. Of course you need to prevent hierarchy cycles.

**Comment by espaan** [comment]
Hi, for me permission based on collections would be great. I have a photo club website running Wordpress that would be ideal to convert (in due time) to zikula. Galleries are per user or per group accessible on that site.

**Comment by ftree** [comment]
It is also possible to use the xsendfile module from apache (https://tn123.org/mod_xsendfile/) for different permissions. I use it on my site that only logged in users can  watch a video (witch is stored outside the Documentroot). At the end of the link you can see how it works.
Its very easy. (if the modul is installed in Apache on the server).

But the big advantage is that you can store the content outside the Document Root and you dont need to stream it by yourself to the client.

Maybe as an additional option the admin can activate ...

**Comment by cmfcmf** [comment]
> It is also possible to use the xsendfile module from apache (https://tn123.org/mod_xsendfile/) for different permissions. I use it on my site that only logged in users can watch a video (witch is stored outside the Documentroot). At the end of the link you can see how it works.
> Its very easy. (if the modul is installed in Apache on the server).

Interesting! I didn't know about this Apache module. It certainly solves performance issues when files are saved outside the document root. Symfony also has something built in, I will take a look: https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/HttpFoundation/BinaryFileResponse.php#L192

> But the big advantage is that you can store the content outside the Document Root and you dont need to stream it by yourself to the client.
> Maybe as an additional option the admin can activate ...

Right, will need to add an option for it.
 
> .) Even though files are watermarked, they are still available non-watermarked. Users could try to guess the URL and access the un-watermarked files.
> 
> With this you can solve this problem ...

Yes, indeed :-)

**Comment by rallek** [comment]
The permissions per collection is the most wanted permission at the moment. Might be you can simplify it if you make the permission depending on root collections. All content inside the root collection is than managed by the permission of it, incl. sub collections.

**Comment by cmfcmf** [comment]
A permission system for collections has been implemented and will be available as of the next release.

**Comment by rallek** [comment]
great!

**Comment by craigh** [comment]
> tree structures are (IMO) inherently difficult to apply permissions to.

apparently I was right about that :boat: :wink:
