### ISSUE TITLE
Calling MediaModule tries to load api.github.com, does not work behind firewall

### ISSUE THREAD

**Issue by espaan** [cmfcmf/MediaModule#21]
Hi
just installed 1.0.1 on zk141b93 and calling http://localhost/zk141b93/collections/settings
I'm testing on localhost behind a firewall and proxy and cannot access internet easily. 
The error I get is:
```

Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

An exception has been thrown during the rendering of a template ("[curl] 7: Failed to connect to api.github.com port 443: Timed out [url] https://api.github.com/rate_limit") in "C:\Apps\xampp\htdocs\zk141b93\modules\cmfcmf\media-module/Resources/views/Base.html.twig" at line 8.
```

**Comment by cmfcmf** [comment]
I will need to add a try/catch block there. You can comment the following code as a temporary workaround: https://github.com/cmfcmf/MediaModule/blob/9d755700aa9b8820b7fdbe27bafe6fdab768fc7c/Twig/TwigExtension.php#L60-L74

**Comment by espaan** [comment]
Hi I now commented out temporarily in the twig template. Base.html.twig put comments around the 
```
{% block upgradeNotification %}
...
```
