### ISSUE TITLE
Suggest / require certain PHP extensions

### ISSUE THREAD

**Issue by espaan** [cmfcmf/MediaModule#23]
When I try to upload media in xampp windows I get the attached error message. 
Could very well be setup issue, but I didnt realize I might not have php_fileinfo on.

![newmedia_phpfileinfo_message_cmfcmf_mediamodule_zk141b93_20151027](https://cloud.githubusercontent.com/assets/349093/10760312/3e08324e-7cbc-11e5-8bfa-41bf0ddd7140.jpg)

**Comment by espaan** [comment]
Hi, yes this is related to php_fileinfo. This should be enabled to enable getID3 and hte mime type extraction. So not really a bug, but might be good to mention in the settings or in the Readme.

**Comment by cmfcmf** [comment]
Yes, indeed. It's not only that certain PHP extensions are required, but some might be suggested to turn on.

**Comment by cmfcmf** [comment]
The module should also warn the user if `post_max_size` or `upload_max_filesize` are too low.
