### ISSUE TITLE
Strip trailing slashes from slugs

### ISSUE THREAD

**Issue by cmfcmf** [cmfcmf/MediaModule#30]
This link works: http://test.de/collections/show/jahrgangsbilder/bilder-2005
This link doesn't: http://test.de/collections/show/jahrgangsbilder/bilder-2005/

**Comment by cmfcmf** [comment]
Or maybe don't strip the slash but redirect? Thoughts? @guite @craigh

**Comment by craigh** [comment]
Don't generate links with a trailing slash in the first place?

**Comment by cmfcmf** [comment]
Sorry, to clarify: I don't generate such links. It just occured to me when I manually changed the url in the address bar.

**Comment by craigh** [comment]
There is already a core listener to remove trailing slashes. Does it not function in this case? If not, why not?

**Comment by cmfcmf** [comment]
Because the route is defined as: ` @Route("/show/{slug}", requirements={"slug"=".+"}, options={"expose" = true})`. Notice how the slug allows *every* character, *including* (trailing) slashes.

**Comment by cmfcmf** [comment]
Aha! Maybe it could be changed to ".*[^/]" to disallow trailing slashes and use the core redirect handler instead.
