### ISSUE TITLE
more options for text based watermark

### ISSUE THREAD

**Issue by rallek** [cmfcmf/MediaModule#31]
it would be great to have 
- [x] a transparent background option
- [x] selection for font color
- [x] selection for background color
- [x] a preview of the offered font

**Comment by cmfcmf** [comment]
The font preview was already implemented but had a bug. It's fixed now.l

**Comment by cmfcmf** [comment]
See https://github.com/cmfcmf/MediaModule/commit/c6984fd0ead214cfef28c91cee9e86c7f221b3b4.

**Comment by cmfcmf** [comment]
Note to self: https://github.com/cmfcmf/MediaModule/blob/6a257bec451f24a520be3238a9386b719086099e/Entity/Watermark/TextWatermarkEntity.php#L71-L77
