### ISSUE TITLE
use a lightbox for images

### ISSUE THREAD

**Issue by rallek** [cmfcmf/MediaModule#34]
special in mobil devices you want to click on images instead of links.

Would be great to have a lightbox which is implementing the typical behavior of mobile devices.

**Comment by cmfcmf** [comment]
Suggested by @rallek and looks pretty good indeed: https://github.com/dimsemenov/photoswipe

**Comment by Guite** [comment]
IMO this can be closed because the lightGallery template is providing the same functionality.
