### ISSUE TITLE
Connection problem? 

### ISSUE THREAD

**Issue by KratorD** [cmfcmf/MediaModule#35]
Hello.

ZK 1.4.1 new install, MediaModule 1.0.3 new install.
Frontend (user):
Error 404
"Page not found"
Backend (Admin panel):
Error 500
"An exception has been thrown during the rendering of a template ("[curl] 7: Failed to connect to api.github.com port 443: Connection refused [url] https://api.github.com/rate_limit") in "C:\xampp\htdocs\test141\modules\cmfcmf\media-module/Resources/views/base.html.twig" at line 8."

**Comment by cmfcmf** [comment]
Hi Krator, this is a known issue, see https://github.com/cmfcmf/MediaModule/issues/21. I'll try to fix it ASAP.

**Comment by cmfcmf** [comment]
@KratorD this is now fixed in version 1.0.4.

**Comment by KratorD** [comment]
Thanks cmfcmf.
PD: I unknow this module. I think that this module must be publish (blog entry) in zikula.org for others users. I was thinking that ZK have not Media Module...
For other hand, it will be possible install MediaModule with the old gallery from Mediashare any day?

**Comment by cmfcmf** [comment]
I have not yet written a blog post, because I was waiting for the release of Zikula 1.4.1 (the module doesn't work with Zikula 1.4.0). But now that Zikula 1.4.1 is released, I'm going to write a blog post when I find time.

**Comment by craigh** [comment]
:watch:

**Comment by KratorD** [comment]
About MediaShare feature?

**Comment by cmfcmf** [comment]
No, not about MediaShare, but about the initial release.
I'll try to look at MediaShare sometime in the future.

KratorD <notifications@github.com> schrieb am Mo., 30. Nov. 2015 14:54:

**Comment by cmfcmf** [comment]
I've now written a block post: http://zikula.org/blog/display/2015/12/3/media-module.
