### ISSUE TITLE
Problem with mime types?

### ISSUE THREAD

**Issue by KratorD** [cmfcmf/MediaModule#36]
ZK 1.4.1 new install, MediaModule 1.0.4 new install.
When I try upload a file (image, video...), I get the error "Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?)"

Do I have to change any configuration of Apache/php ? (FYI: Localhost in Windows with XAMPP)

Thanks.

**Comment by cmfcmf** [comment]
This is a duplicate of https://github.com/cmfcmf/MediaModule/issues/23. The module currently requires the `fileinfo` PHP extension. It's planned to display a warning if the extension is not enabled or find a way to not require it. 

I think @espaan also uses Xampp and was able to enable it.

**Comment by KratorD** [comment]
Ok, thanks, I have actived the file extension in my localhost and the image was upload.
Sorry.

**Comment by cmfcmf** [comment]
Cool, no need to say sorry though! :-)

**Comment by espaan** [comment]
Hi, yep I could just enable it by going to the php.ini file and looking for fileinfo. 
IIRC the extension=php_fileinfo.dll was disabled by default.
