### ISSUE TITLE
Allow to sort root collections

### ISSUE THREAD

**Issue by rallek** [cmfcmf/MediaModule#38]
pictures I can reorder bey drag and drop. It would be great if I am able to do the same with subcollection.

**Comment by cmfcmf** [comment]
This should be easy to add and implement.

I'm glad you found the sorting functionality for media, because the arrows
are a little hidden.

rallek <notifications@github.com> schrieb am Mo., 7. Dez. 2015 11:37:

**Comment by cmfcmf** [comment]
With the coming release, you can now also sort subcollections. You can't, however, sort root collections. This is a little more difficult and will be implemented later on.

**Comment by rallek** [comment]
:+1:

**Comment by rallek** [comment]
unfortunately the sorting of collections is not working as expected. I am able to grab a collection (2nd level) with the mouse but dropping do have no effect (Forbidden symbol is visible).

**Comment by cmfcmf** [comment]
I'm guessing that you weren't logged in when you tried. Apparently, the JavaScript to sort the collections and images is loaded *regardless* of whether you have permission to sort or not.

**Comment by rallek** [comment]
nope, I am logged in.

**Comment by cmfcmf** [comment]
Could you please do the following steps:
1. Open your browser's console and check for a JavaScript error when you try to sort.
2. If there is none, use your browser's console to inspect the failing ajax request. Maybe also switch to dev mode.

**Comment by rallek** [comment]
after deleting the /prod and the /dev folders I am able to drag and drop collection. I think the core do have a caching issue.
