### ISSUE TITLE
Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by shefik** [cmfcmf/MediaModule#42]
Error at `/collections/settings`:

```Warning: require_once(/modules/MediaModule/Upgrade/../vendor/autoload.php): failed to open stream: No such file or directory in /modules/MediaModule/Upgrade/VersionChecker.php on line 186```

**Comment by cmfcmf** [comment]
Did you use the development version from GitHub? You need to run composer
update then.

Shefik <notifications@github.com> schrieb am Mi., 9. Dez. 2015 09:02:
