### ISSUE TITLE
Add view counter to media and collections

### ISSUE THREAD

**Issue by cmfcmf** [cmfcmf/MediaModule#5]

**Comment by espaan** [comment]
Adding an optional view counter (yes/no enabled) for Collections would be great as well.

I would make it settable to count yes/no

**Comment by cmfcmf** [comment]
This has been implemented but isn't currently displayed anywhere.

**Comment by Guite** [comment]
Don't know how it is currently done, but for improved performance it would be advantageous if new values were not directly saved into the database, but temporarily collected elsewhere (e.g. in a text file). The collected values are then moved into the database on a regular basis. The benefit from that is that not every request causes a database write operation (which could block read operations and therewith makes problems with scalability).

**Comment by cmfcmf** [comment]
The view counters can now be disabled to improve performance.
