### ISSUE TITLE
[1.1.0] creating permissions do not work

### ISSUE THREAD

**Issue by rallek** [cmfcmf/MediaModule#58]
the module own permission do have the option to create new permissions. If I click on the + a modal window opens. I can select group and click on ``create permisson``. Nothing happens than.

I am working in multilingual environment. The modal and so on is still in english. I don't know if this do have an influence.

**Comment by cmfcmf** [comment]
Please check for errors in the JavaScript console (open with F12 in most browsers).

**Comment by rallek** [comment]
````
Error: The route "cmfcmfmediamodule_permission_new" does not exist.
http://oldtimer-ig-osnabrueck.de/web/bundles/fosjsrouting/js/router.js
Line 9
````

**Comment by rallek** [comment]
at the column ``action`` I do have only the + and no other icons for changes

**Comment by rallek** [comment]
in dev env. I can add a permission

**Comment by craigh** [comment]
The routes js file sounds not created for prod

**Comment by rallek** [comment]
![collection permission](https://cloud.githubusercontent.com/assets/935250/13204198/4dade88c-d8ca-11e5-901b-0548f9769ce2.jpg)
With this permission the member of the group Beitragsmoderatoren is not able to do anything but view and download the media items in that collection.

All Guests are able to view.

It doesn't matter if env is prod or dev

**Comment by rallek** [comment]
Now switching back to prod I am able to add media items.
