### ISSUE TITLE
[1.1.0] po files are not complete

### ISSUE THREAD

**Issue by rallek** [cmfcmf/MediaModule#59]
all available items are translated but still some are in english

**Comment by cmfcmf** [comment]
This is blocked by vendor issues in the JMS Translation bundle. I can't currently extract translations without problems. The issues however should soon be fixed now that the bundle is actively maintained again.

**Comment by rallek** [comment]
https://github.com/schmittjoh/JMSTranslationBundle/releases/tag/1.2.1 This one?

**Comment by cmfcmf** [comment]
> https://github.com/schmittjoh/JMSTranslationBundle/releases/tag/1.2.1 This one?

Not quite. 1.2.2 is probably the one. :smile:

**Comment by rallek** [comment]
https://github.com/schmittjoh/JMSTranslationBundle/releases Now we are already at 1.3.x :smile:
