### ISSUE TITLE
Invalid vertex ID

### ISSUE THREAD

**Issue by KratorD** [cmfcmf/MediaModule#61]
Hello.

ZK 1.4.1. Download MM 1.1.0 release from git releases. Fresh install of module. Show frontend:

> An exception has been thrown during the rendering of a template ("Invalid vertex ID") in "CmfcmfMediaModule:Collection:display.html.twig" at line 39.

**Comment by cmfcmf** [comment]
I cannot reproduce this issue. I did a fresh install of Core 1.4.1 and the MediaModule 1.1.0 (both taken from the GitHub Releases).
