### ISSUE TITLE
Upgrade on a 1.4.1 site failed

### ISSUE THREAD

**Issue by rallek** [cmfcmf/MediaModule#68]
after starting upgrade script I do get the following:
![zwischenablage01](https://cloud.githubusercontent.com/assets/935250/13996598/d4b4790a-f12e-11e5-93ea-7ffcd24bc8bc.jpg)
The Module is not available anymore on that site

In extensions I can see there should be a new version 1.1.1. After clicking on the upgrade symbol I do get the following error:

Fatal error: Class 'Zikula\Core\AbstractExtensionInstaller' not found in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.1/modules/cmfcmf/MediaModule/MediaModuleInstaller.php on line 22

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'RecursiveDirectoryIterator::__construct(//var/lib/polkit-1): failed to open dir: Permission denied' in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.1/vendor/symfony/symfony/src/Symfony/Component/Debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php:148 Stack trace: #0 [internal function]: RecursiveDirectoryIterator->__construct('//var/lib/polki...', 4096) #1 /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.1/vendor/symfony/symfony/src/Symfony/Component/Debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php(148): RecursiveDirectoryIterator->getChildren() #2 /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.1/vendor/symfony/symfony/src/Symfony/Component/Debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php(117): Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler->findClassInPath(false, 'AbstractExtensi...', 'ZikulaSecurityC...') #3 /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.1/vend in /home/www/www.oldtimer-ig-osnabrueck.de/Zikula_Core-1.4.1/vendor/symfony/symfony/src/Symfony/Component/Debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php on line 148

**Comment by cmfcmf** [comment]
Sorry for the inconvenience, apparently the newly used `AbstractExtensionInstaller` class is only available in Core 1.4.2. I will re-release 1.1.1 when Core 1.4.2 is out.

**Comment by craigh** [comment]
> apparently the newly used `AbstractExtensionInstaller` class is only available in Core 1.4.2

correct.
