### ISSUE TITLE
explain how to translate

### ISSUE THREAD

**Issue by rallek** [cmfcmf/MediaModule#7]
I can not find any place of a pot file or even the loacle folder is not there. So it looks like another translation concept than I am used to. Please provide some documentation how to translate your module.

**Comment by cmfcmf** [comment]
Translations have been added: https://github.com/cmfcmf/MediaModule/tree/master/Resources/translations

**Comment by cmfcmf** [comment]
But please note that translations coming from JavaScript aren't translated due to a Core issue: https://github.com/zikula/core/issues/2601

**Comment by rallek** [comment]
The translation looks still different from what I know. Is there any place where I can found more information about folder and file name structure?

**Comment by cmfcmf** [comment]
There is a bit of it in here: https://github.com/zikula/core/blob/1.4/src/docs/en/dev/zikula_sf_translator.md

**Comment by rallek** [comment]
Thanks. That givey me my answer
