### ISSUE TITLE
1.4.3 RC testing: cannot install MediaModule 1.2

### ISSUE THREAD

**Issue by MrMontesa** [cmfcmf/MediaModule#74]
I just tested installation of MediaModule on the new 1.4.3 RC and it did not work for me.
I grabed [this download](https://github.com/cmfcmf/MediaModule/releases/download/1.2.0/MediaModule.zip), and when executing the installer I receive the following error message:
The server returned a "500 Internal Server Error

`An exception occurred while executing 'INSERT INTO cmfcmfmedia_collection (title, slug, description, views, downloads, defaultTemplate, createdUserId, updatedUserId, createdDate, updatedDate, lft, rgt, lvl, root, primaryMedium_id, parent_id, watermark_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["Temporary upload collection", "tmp", "This collection is needed as temporary storage for uploaded files. Do not edit or delete!", 0, 0, null, null, null, null, null, null, null, null, null, null, null, null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'createdUserId' cannot be null`

Let me know if you need more details.

**Comment by cmfcmf** [comment]
I cannot reproduce this error. I installed a fresh copy of Zikula 1.4.3-rc3 and downloaded the 1.2.0 release of the MediaModule. I then extracted it to `modules/cmfcmf/media-module/{MediaModuleInstaller,composer.json,...}` and installed it just fine.

**Comment by MrMontesa** [comment]
hmm, wired. Only difference is that I installed it to modules/MediaModule/.
My testbed is publicity available. In case direct access may help you, I can add an admin user to troubleshoot.

**Comment by cmfcmf** [comment]
> Only difference is that I installed it to modules/MediaModule/.

I just tried that as well, and it worked. :confused: 
> My testbed is publicity available.

I am unsure whether this would help me. Can you try to remove everything inside your `app/cache/prod` folder and try again? If that doesn't work either, please try setting `env: dev` and `debug: true` inside `app/config/custom_parameters.yml`.

**Comment by MrMontesa** [comment]
After some more testing and discussion we agreed on this must have been an issue with the local Zikula Installation. After re-installing ZK and giving it another try, this problem was not reproducible any more.
Closing
