### ISSUE TITLE
Add categories?

### ISSUE THREAD

**Issue by cmfcmf** [cmfcmf/MediaModule#8]
Do you feel the need to make media and collections categorizable using Zikula Categories? If so, could you please explain why?

**Comment by Guite** [comment]
It could be useful for enhanced integrations. Let's say you have another module (for example a webshop) and you want to include media based on the current category. But not urgent imo.

**Comment by craigh** [comment]
Content Module has built in category by page functionality which might be a use case here.

**Comment by rallek** [comment]
If there is a content plugin for a collection the category is not needed here.

But if we have a category by media and do have a block/content plugin we would be able to filter by category inside a collection. Nice possibility but I am still looking for its use case.

I think this is not needed for 1.x. Let us see if we find later a use case.
