### ISSUE TITLE
navigation locked in MediaModule

### ISSUE THREAD

**Issue by MrMontesa** [cmfcmf/MediaModule#82]
Hey,
When accessing MediaModule frontend I can properly navigate through all collections etc. But I'm not able to switch to a different module at all. All relative path's set in menues have /media/ prepended.
In fact any link keeps you within the module. I tested this with Andreas08 and the new vootstrap theme within ZK 1.4.3.

Reproduce:
- install zk 1.4.3 & use Andreas08 theme
- extend existing menu to point to a different extension. E.g News
- install MediaModule 1.2.1
- enter MediaModule & navigate to a collection
- hover over any link pointing to other modules configured with relative path

**Comment by cmfcmf** [comment]
I am not entirely sure if this is a MediaModule issue. Make sure to use full link patjs starting with a `/` if you add links to other modules.

**Comment by MrMontesa** [comment]
Hmm, cant re-procude either right now. Possibly some bad cache that I deleted when testing something else.
Thanks for checking.

**Comment by cmfcmf** [comment]
> Hmm, cant re-procude either right now. Possibly some bad cache that I deleted when testing something else.
> Thanks for checking.

Glad to hear - new release with the translation fixes coming soon.
