### ISSUE TITLE
Cant upload media when language is changed

### ISSUE THREAD

**Issue by MrMontesa** [cmfcmf/MediaModule#83]
Hey I just finished translation for german which can be grabbed from my [fork](https://github.com/MrMontesa/german/tree/core-1.4). 
When changing the default language to german, I'm no longer able to upload media.
A red info window will apprear on the upper right hand side, stating "There was an AJAX error. Try again".
But nothing changes until I do revert the language back to english again.

Feel free to also test this on my testbed available @ http://staging.amc-idstein.de
Let me know if I can be of any help.

**Comment by cmfcmf** [comment]
This should now be fixed.
