### ISSUE TITLE
upgrade message is old

### ISSUE THREAD

**Issue by rallek** [cmfcmf/MediaModule#84]
I have upgraded the classic way via delete files, add newest files and run upgrade within the extensions. Now I do have version 1.2.1 but I do get the message:
````
The 1.1.1 version of the MediaModule is available for download. You can apply the automatic upgrade by clicking here: Upgrade now!
````
If I run the upgrade it is telling me nothing to upgrade but the message did not disapear

**Comment by cmfcmf** [comment]
This should now be fixed.
