### ISSUE TITLE
the upgrade of 1.4.6 to 1.5.0 failed

### ISSUE THREAD

**Issue by rallek** [cmfcmf/MediaModule#94]
during QA testing in https://github.com/zikula/core/issues/3686 I do have a problem with MediaModule.
As long as the module is available in cmfcmf folder I do get an error message before anything happens in the upgrade:
´´´´
Fatal error: Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Catchable Fatal Error: Argument 2 passed to Cmfcmf\Module\MediaModule\Twig\TwigExtension::__construct() must be an instance of Zikula_HookDispatcher, instance of Zikula\Bundle\HookBundle\Dispatcher\HookDispatcher given, called in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/app/cache/prod/appProdProjectContainer.php on line 3120 and defined' in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/modules/cmfcmf/Twig/TwigExtension.php:63 Stack trace: #0 /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/modules/cmfcmf/Twig/TwigExtension.php(63): Symfony\Component\Debug\ErrorHandler->handleError(4096, 'Argument 2 pass...', '/www/htdocs/w01...', 63, Array) #1 /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/app/cache/prod/appProdProjectContainer.php(3120): Cmfcmf\Module\MediaModule\Twig\TwigExtension->__construct(Object(Michelf\MarkdownExtra), Object in /www/htdocs/w0172993/2017.oldtimerigosnabrueck.de/Zikula_Core-1.5.0/modules/cmfcmf/Twig/TwigExtension.php on line 63
´´´´
The cache was deleted before

after deleting the cmfcmf folder I can start the upgrade process. But that faild also due to other reasons

**Comment by cmfcmf** [comment]
Looks like the module currently isn't compatible with Zikula 1.5. 😞

**Comment by rallek** [comment]
Hook was rewritten. Might be it is a core issue?

**Comment by cmfcmf** [comment]
The `@hook_dispatcher` service class has changed inside the core. Depending on the core's deprecation / versioning policy, you *could* call it a core issue. The fix would probably have to be done inside the MediaModule: Typehint the `HookDispatcherInterface` instead of `Zikula_HookDispatcher`. I'll see if I can work it out.

**Comment by craigh** [comment]
@cmfcmf I briefly glanced through the core and looked for usages of `Zikula_HookDispatcher` and found none. So, I _think_ one solution here (in the core) would be to alias `Zikula_HookDispatcher` to `Zikula\Bundle\HookBundle\Dispatcher\HookDispatcher` to maintain BC but I am not sure about this. opinions? @Guite

**Comment by Guite** [comment]
In the generator I use:

* `Zikula\Component\HookDispatcher\HookDispatcher` for 1.4.x
* `Zikula\Bundle\HookBundle\Dispatcher\HookDispatcher` for 1.5+

I guess `Zikula_HookDispatcher` is 1.3.x style, isn't it?

**Comment by craigh** [comment]
there is no `HookDispatcher` directory in 1.4

https://github.com/zikula/core/tree/1.4/src/lib/Zikula/Component

**Comment by craigh** [comment]
ah - I see it was at least in 1.4.0

https://github.com/zikula/core/tree/1.4.0/src/lib/Zikula/Component

**Comment by Guite** [comment]
Good point.

In the `1.4` branch we have:

* `Zikula_HookDispatcher` at https://github.com/zikula/core/blob/1.4/src/lib/legacy/Zikula/HookDispatcher.php which was deprecated in 1.4.0
* `Zikula\Bundle\HookBundle\Dispatcher\HookDispatcher` at https://github.com/zikula/core/blob/1.4/src/lib/Zikula/Bundle/HookBundle/Dispatcher/HookDispatcher.php

**Comment by craigh** [comment]
Well, the original plan was to use `Zikula_HookDispatcher` until 2.0 but that changed when I installed all the non-persistent hook stuff. I had previously written the new HookDispatcher long ago, but it wasn't being used at all - with the plan to install it at 2.0 (this was 3 years ago or something - probably with the release of 1.4.0). 

Anyway - what is the best way forward here? I am interested in maintaining BC in the 1.5 branch if possible. I'm just concerned that if the `Zikula_HookDispatcher` class entirely disappears and is replaced by the new as an alias, then something else might break....

**Comment by Guite** [comment]
Would it maybe be possible to reintroduce `Zikula_HookDispatcher` in `lib/legacy/Zikula/.../`?

**Comment by craigh** [comment]
what would be its contents? I think it would be easier to just alias like https://github.com/zikula/core/blob/1.5/src/app/autoload.php#L37-L49

**Comment by Guite** [comment]
Reasonable imo.

**Comment by craigh** [comment]
lol. `Zikula_HookDispatcher` exists in 1.5

https://github.com/zikula/core/blob/1.5/src/lib/legacy/Zikula/HookDispatcher.php

so, I guess the method here would be to remove then alias...

**Comment by craigh** [comment]
The issue here is that MediaModule injects `@hook_dispatcher` which used to be `Zikula_HookDispatcher` and is now `Zikula\Bundle\HookBundle\Dispatcher\HookDispatcher`

https://github.com/cmfcmf/MediaModule/blob/master/Resources/config/services.yml#L100

**Comment by craigh** [comment]
this feels wrong.

this is an important part of the old dispatcher

https://github.com/zikula/core/blob/1.5/src/lib/legacy/Zikula/HookDispatcher.php#L291-L319

this is apparently not being used at the moment. I don't think this is correct.

removing and aliasing would be wrong if this method is required.

**Comment by Guite** [comment]
I guess the problem would go away if the typehint would use `HookDispatcherInterface` instead of `Zikula_HookDispatcher`?

**Comment by craigh** [comment]
this issue would, sure but that means BC is broken

**Comment by Guite** [comment]
I doubt that this is solvable in a clean way. The only possible approach I could think of (in theory) is that `@hook_dispatcher` resolves to `Zikula_HookDispatcher` again, while a new service (`@hook_dispatcher_new` :p) is created in addition.

**Comment by craigh** [comment]
I'm looking at that atm

**Comment by craigh** [comment]
This should be fixed in the core now.

@rallek please test with newest core builds

@cmfcmf assuming is fixed, please close the ticket

**Comment by rallek** [comment]
test is successfull! Great job!
